### PR TITLE
Redirect calls to printf and fprintf

### LINKED ISSUE #112: printf output not redirected
If I do 

```
#include <stdio.h>
printf("testing")
```

In the notebook, I get the return value of the `printf` function which in this case is 

```
(int) 7
```
but the string `testing` does not appear anywhere.

This, in turn, causes problems when trying to use a C library that makes use of `printf`.  Functions that were verbose in real usage are silent in the notebook.

### PR DESCRIPTION
**Pull request by hahnjo**
When the interpreted code calls an external function, LLVM will use
`dlsym()` to find the target in the current process. This works well
for functions from libc which are always loaded.
However this also outputs the result of `printf()` and `fprintf()` to the
terminal and does not forward it to the user. This is very unintuitive
because values piped into `std::cout` and `std::cerr` correctly appear in
the browser.

As a solution, use `llvm::sys::DynamicLibrary::AddSymbol()` to inject
custom implementations into the process of finding external functions.
Once hooked up, the implementations format the passed arguments into
a C++ string and forward the result to the C++ streams that correctly
forward to the user.

Fixes #112

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This is *great*!

**Comment by JohanMabille** [comment]
Thanks a lot!

**Comment by SimeonEhrig** [comment]
@hahnjo 
Sorry for the delay. I was very busy last week. Great Work!

From PR #293 
> As far as I know, it's undefined behavior to redefine standard functions like `printf`. Instead I've independently developed a different solution in #315 that injects custom implementations (very similar to this PR) into the process of calling external functions from interpreted code.

Yes, it's similar to my idea, but you solved my last problem, the os dependency, in a really clever way.

I have also a possible improvement for your implementation. When, I use `fprintf(stdout, "Hello World!\n");` it prints to the terminal, but I would expect, that it prints to the browser. It's just a small fix.

Thank you very much for your work. It helps me a lot with our old school developers ;-)

**Comment by hahnjo** [comment]
@SimeonEhrig 
> I have also a possible improvement for your implementation. When, I use `fprintf(stdout, "Hello World!\n");` it prints to the terminal, but I would expect, that it prints to the browser. It's just a small fix.

Yes, the code in `fprintf_jit` should likely handle the case of `stream == stdout`, good thought.

**Comment by hahnjo** [comment]
> > I have also a possible improvement for your implementation. When, I use `fprintf(stdout, "Hello World!\n");` it prints to the terminal, but I would expect, that it prints to the browser. It's just a small fix.
> 
> Yes, the code in `fprintf_jit` should likely handle the case of `stream == stdout`, good thought.

See #320 for the obvious follow-up.

**Pull request merged**
