### PR TITLE
Make xcpp*/kernel.json.in subsitution more portable

### PR DESCRIPTION
**Pull request by serge-sans-paille**
According to https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

CMAKE_INSTALL_BINDIR can be either absolute or relative. Make sure we use the absolute value through CMAKE_INSTALL_FULL_BINDIR.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
this is a wip, I still need to sort out a few thing, pelase wait before considering reviewing this PR

**Comment by serge-sans-paille** [comment]
no longer a wip, feel free to review :-)

**Comment by SylvainCorlay** [comment]
I can't find a reference to `CMAKE_INSTALL_FULL_BINDIR` in the cmake documentation!

**Comment by JohanMabille** [comment]
[here](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) you have documentation for the generic `CMAKE_INSTALL_FULL_<dir>`.

**Comment by SylvainCorlay** [comment]
> [here](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) you have documentation for the generic CMAKE_INSTALL_FULL_<dir>.

Great, then we should go ahead and make the fix in all xeus-based kernels.

**Pull request merged**
